version: "2.4"
networks:
  traefik:
    external: true

services:
  pedropedia:
    build:
      context: ./pedropedia
      dockerfile: docker/Dockerfile
    image: pedropedia
    container_name: pedropedia
    environment:
      - MAX_WORKERS=4
    env_file:
      - .env
    volumes:
      - ./pedropedia/data:/var/lib/pedropedia
    expose:
      - "80"
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pedropedia.rule=Host(`pedvide.duckdns.org`, `pedropedia.com`, `www.pedropedia.com`)"
      - "traefik.http.routers.pedropedia.entrypoints=web"
      - "traefik.http.routers.pedropedia-secure.rule=Host(`pedvide.duckdns.org`, `www.pedropedia.com`)"
      - "traefik.http.routers.pedropedia-secure.entrypoints=websecure"
      - "traefik.http.routers.pedropedia-secure.tls.certresolver=lets-encr"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.permanent=true"
      - "traefik.http.routers.pedropedia.middlewares=redirect-to-https"
      - "traefik.docker.network=traefik"
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 500M
    restart: unless-stopped

